### PR TITLE
opt-in to allow use of host files not expressly supplied as inputs

### PR DESCRIPTION
**Pull request by mlin**

### CODE REVIEW

**Comment by mlin** [comment]
@rhpvorderman this is a more-complete version of #582 which provides opt-in to using arbitrary host files by setting [file_io] allow_any_input = true. Because this has a security impact, I think it's necessary for the opt-in to come from the miniwdl operator rather than the WDL author.

This handles the case of non-input files being used at the workflow level and passed to tasks, but not if a task tries to use something that wasn't passed to it by the workflow. The latter case (i) wasn't needed to unblock you IIRC, (ii) I'm not sure if Cromwell supports that either, and (iii) is enforced in a separate part of the codebase so we can always come back to it later.

**Comment by rhpvorderman** [comment]
@mlin thanks so much for your quick action. I have tested it immediately on our Germline-DNA workflow test. 
It works but there is one problem:
```
MINIWDL__FILE_IO__ALLOW_ANY_INPUT=true miniwdl run -i tests/integration/Germline_PairedEnd.json germline.wdl
... 
 task Fastqc (tasks/fastqc.wdl Ln 23 Col 1) failed :: dir: "/home/rhpvorderman/PycharmProjects/germline-DNA/20220810_103712_Germline/call-sampleWorkflow-1/call-qualityControl-1/call-FastqcRead1", error: "RuntimeError", message: "docker task rejected: invalid bind mount source, must be an absolute path: tests/data/wgs2/wgs2-lib2_R1.fq.gz"
```

Any files from the `inputs.json` are correctly made absolute, but not any files from other sources.

I think this can be easily fixed with an `os.path.abspath` inside the mounting code.

**Comment by rhpvorderman** [comment]
> The latter case (i) wasn't needed to unblock you IIRC, (ii) I'm not sure if Cromwell supports that either, and (iii) is enforced in a separate part of the codebase so we can always come back to it later.

No indeed, I feel like using an external samplesheet is very legitimate given JSON's less than pleasant human-editability, but otherwise we make our inputs as explicit as possible. Having to literally specify the index file for a reference fasta is not really a major cause of work or annoyance.

**Comment by mlin** [comment]
@rhpvorderman good catch, updated

**Comment by rhpvorderman** [comment]
Tested both docker and singularity backends on the germline-DNA pipeline and both work excellently. Great!

**Pull request merged**
