### PR TITLE
Add support for attaching tasks to docker networks.

### PR DESCRIPTION
**Pull request by jgadling**
### Motivation
We increasingly rely on miniwdl in our batch processing pipelines, and we're currently trying to improve the developer experience for engineers who work on those pipelines. Our local development environments make use of `docker-compose` and docker networks to make the interactions between our microservices resemble our production environment. Since miniwdl doesn't currently have support for docker networks, the tasks it runs don't have access to the services in our local dev environment and can't interact with our local S3 service, database, etc.

### Approach
This is a pretty straightforward addition of a `docker_network` runtime config flag.

### Checklist

- [x] Add appropriate test(s) to the automatic suite
- [x] Use `make pretty` to reformat the code with [black](https://github.com/python/black)
- [x] Use `make check` to statically check the code using [Pyre](https://pyre-check.org/) and [Pylint](https://www.pylint.org/)
- [x] Send PR from a dedicated branch without unrelated edits
- [x] Ensure compatibility with this project's MIT license

### CODE REVIEW

**Comment by jgadling** [comment]
Yeah, I don't mind updating this -- do you think it would be better to make it a top level setting, vs this version? I'm pretty sure this one works with the following env var set: `MINIWDL__TASK_RUNTIME__DEFAULTS={"docker_network":"my_network"}`

**Comment by mlin** [comment]
@jgadling That's a great point about using the runtime defaults!

Coincidentally last week somebody had asked me about enabling host networking, so I added a test case for setting `docker_network: "host"`, which seemed to just work.

**Comment by jgadling** [comment]
any barriers to merging this?

**Review by mlin — APPROVED** [review]

**Comment by mlin** [comment]
@jgadling I just tweaked the docs a bit and it reminded me of one last question I think is fine, but I thought I'd run by you:

Although we'd never recommend running untrusted WDL code, we configure the docker containers so that a malicious WDL wouldn't be able to access any host files/data except the provided inputs (barring container-escape vulnerabilities, of course).

[Recently we added](https://github.com/chanzuckerberg/miniwdl/pull/537/files) a `runtime.privileged` setting to allow some of Shasta's performance optimizations, which opens all sorts of holes; so we required also that the operator should have to set an enabling configuration option, `[task_runtime] allow_privileged = true` for that runtime entry to work. So while an evil WDL author could write `privileged: true` in their task, this way at least the operator also has to opt-in to allowing that.

I was just trying to think of whether there are such security/isolation concerns with the docker networking, where we wouldn't want some untrusted code having the potential to touch it (by default). I didn't come up with much, but wanted to run it by you since I have less experience with it. By setting `docker_network: "host"` you could then listen on any available port (including <1024) -- not something that'd keep me up at night

**Comment by jgadling** [comment]
> I was just trying to think of whether there are such security/isolation concerns with the docker networking, where we wouldn't want some untrusted code having the potential to touch it (by default). I didn't come up with much, but wanted to run it by you since I have less experience with it. By setting `docker_network: "host"` you could then listen on any available port (including <1024) -- not something that'd keep me up at night

Allowing a wdl task to specify which network it should to be attached to is 100% in the same security category as enabling the `privileged` flag on a task container. I think that if we're taking precautions for the privileged flag we need to do something equivalent for networking configuration. Should we reuse the `allow_privileged` flag in this case, or do you think it warrants a different setting?

**Comment by jgadling** [comment]
> @jgadling Thanks for that assessment! I put an allowlist config option in there. LMK what you think

This looks great, thanks for adding it!

**Pull request merged**
