### PR TITLE
Remove string interpolator options from development spec + add `sep` function

### PR DESCRIPTION
**Pull request by illusional**
### Motivation

- Primarily: https://github.com/openwdl/wdl/pull/229

### Approach

Followed [Adding WDL functions](https://miniwdl.readthedocs.io/en/latest/add_functions.html) tutorial.

### Checklist

- [x] Add appropriate test(s) to the automatic suite
- [x] Use `make pretty` to reformat the code with [black](https://github.com/python/black)
    - ~~This is currently formatting more than just my change in StdLib.py - so I've disabled it.~~
    - This was being caused by a different version of black, upgrading solved this.
- [x] Use `make check` to statically check the code using [Pyre](https://pyre-check.org/) and [Pylint](https://www.pylint.org/)
- [x] Send PR from a dedicated branch without unrelated edits
- [x] Ensure compatibility with this project's MIT license

---

Calling the `sep` function inside an interpolated line (inside a command block) is failing if it's the only argument inside the block, eg:

I presume this might be a grammar thing, but I don't know how to solve it.

```wdl
command <<<
    # FAILING
    echo ~{sep(",", ["value1", "value2", "value3"])}
    # PASSING
    echo ~{"" + sep(",", ["value1", "value2", "value3"])}
```

### CODE REVIEW

**Comment by mlin** [comment]
Thanks! miniwdl's 'development' [grammar still supports the special 'sep'](https://github.com/chanzuckerberg/miniwdl/blob/cb603b2ed87dacf7c05082e061044641898ec6ea/WDL/_grammar.py#L324) construct in interpolations, so that's the likely cause of the conflict. My understanding is that the old sep is penciled for removal too (https://github.com/openwdl/wdl/pull/229) so this shouldn't be an issue in the long run, but lets carry on a discussion of how to sequence those changes on those PRs.

**Comment by mlin** [comment]
Ok, clarifying my understanding, https://github.com/openwdl/wdl/pull/229 *both* deletes the old `sep=` construct and adds the new `sep()` function. So if we expand this to accomplish the former, it wouldn't have other dependencies.

**Comment by illusional** [comment]
Thanks @mlin, I've realised I linked the wrong PR, and have fixed this. It was supposed to link to the "Clarify the expression placeholder and string interpolation behaviour" (https://github.com/openwdl/wdl/pull/229) PR. 

Per your suggestion and the now correctly linked PR, I've modified the grammar for the development spec to remove all string interpolator options. The implementation would have to remain for previous versions of the spec to work correctly.

I've added some tests into `test_5stdlib.py` and ran 2 / 3 cases in my test, but having some trouble with the one that has a command line binding, I get a docker mount error:

```
RuntimeError: docker task rejected, desired state shutdown: invalid mount config for type "bind": bind source path does not exist: /var/folders/jz/y9gqxt_s7jxcjkc26gr71ywr7zs5yz/T/miniwdl_test_stdlib_ys2hr_wk/20200428_104923_SepTest/command
```

**Comment by mlin** [comment]
@illusional try setting environment `TMPDIR=/tmp` before the tests to get around that problem on macOS. It's because Docker for Mac has a whitelist of host paths that can be mounted into containers, and it doesn't include `/var/folders` unfortunately.

The travis build looks good and the coveralls is an unrelated stochastic fluctuation, nothing to worry about.

**Comment by illusional** [comment]
Hey @mlin, I think this is good to go. 

- `make pretty` is showing warnings for unrelated lines, no warnings cover the changes I've made.
- The `make check` fails with `pyre: error: unrecognized arguments: --show-parse-errors`. I get more unrelated pyre errors about cache files not existing.

But my tests run, so this should be okay.

**Pull request merged**
