### PR TITLE
mount singularity tmpdir in task directory

### PR DESCRIPTION
**Pull request by mlin**

### CODE REVIEW

**Comment by mlin** [comment]
@rhpvorderman here's an even simpler change we can make. For the local case, it usually doesn't make any difference whether the temp directory is mounted under $TMPDIR or the task run directory; and for slurm you want the latter, so we can just always do that.

On reviewing my notes, I recall this remounting of /tmp and /var/tmp was just a workaround to avoid requiring the operator to [edit their singularity.conf](https://docs.sylabs.io/guides/3.5/admin-guide/configfiles.html#session-directory-and-system-mounts) to raise/remove its default 16MB limit. In the future we can add an option to opt *out* of this if the operator is willing & able to edit their singularity.conf.

**Comment by rhpvorderman** [comment]
@mlin that sounds great! Singularity conf can typically not be edited on HPC since the admin controls that file (and they want to use the default config as much as possible, less maintenance). 

I love that after some deliberation, the "least code possible" solution is preferred. This project is very different from Cromwell indeed :wink:! Thanks!

**Comment by rhpvorderman** [comment]
Did a real world test and it works. Great! If this is merged, the miniwdl-slurm plugin can do all its job submission with minimal user intervention.

In fact this is all the configuration that is needed for our pipelines
```
[scheduler]
container_backend=slurm_singularity

[singularity]

run_options = [
        "--containall"
    ]

[file_io]
allow_any_input=true
```
So just setting the run_options to `--containall` only. (The mimick root options do not work on the cluster). Easy peasy.
I will do some real world testing now. And see if anything comes up. If not, I can already release miniwdl-slurm 0.1 at a whopping 85 lines of code! This whole process has been incredibly easy thanks to you, thanks again!

**Comment by mlin** [comment]
Thanks @rhpvorderman, very exciting & I'm looking forward to trying it out too perhaps on AWS ParallelCluster!

I think we have a terrific change set built up for miniwdl v1.7.0 which I'll work on releasing in the next couple of days.

**Pull request merged**
