### PR TITLE
use subworkflow thread pool per call depth level

### PR DESCRIPTION
**Pull request by mlin**

### CODE REVIEW

**Comment by mlin** [comment]
@rhpvorderman here's a go at it...not yet polished or tested

**Comment by rhpvorderman** [comment]
@mlin `MINIWDL__SCHEDULER__SUBWORKFLOW_CONCURRENCY=1 MINIWDL__FILE_IO__ALLOW_ANY_INPUT=true miniwdl run -i tests/integration/Somatic_PairedEnd.json somatic.wdl` runs without deadlocks. (A bit slow though, due to not being able to schedule many jobs in parallel). 

So this PR solves the issue :tada:

**Comment by mlin** [comment]
Thanks @rhpvorderman, yea I added a small test that freezes on main and works with this patch. This is in the integration test scripts rather than the unit tests just because it's more convenient to mock out nested subworkflows there.

**Comment by rhpvorderman** [comment]
Thanks again!

**Pull request merged**
